# Generated by Django 5.0.1 on 2026-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_remove_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='veg_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian')], default='veg', help_text='Vegetarian or Non-Vegetarian', max_length=10),
        ),
    ]

