# Generated by Django 5.0.1 on 2026-01-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_add_veg_type_to_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='veg_type',
        ),
    ]

