# Generated by Django 5.0.1 on 2026-01-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_remove_veg_type_from_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='saved_for_later',
            field=models.BooleanField(default=False, help_text='Save this item for later purchase'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
    ]

