# Generated by Django 5.0.1 on 2026-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_cart_is_selected_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to='profile_photos/'),
        ),
    ]
