# Generated by Django 6.0.1 on 2026-01-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_menuitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-utensils', help_text='FontAwesome icon class (e.g., fa-pizza-slice, fa-coffee)', max_length=50),
        ),
    ]
