# Generated by Django 6.0.1 on 2026-01-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_add_icon_to_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ad_type', models.CharField(choices=[('promo_card', 'Promotional Card'), ('banner', 'Banner Ad'), ('mini_ad', 'Mini Ad')], default='promo_card', max_length=20)),
                ('position', models.CharField(choices=[('home_top', 'Home Page - Top'), ('home_middle', 'Home Page - Middle'), ('menu_sidebar', 'Menu Page - Sidebar'), ('cart_bottom', 'Cart Page - Bottom')], default='home_middle', max_length=20)),
                ('badge_text', models.CharField(blank=True, help_text='e.g., NEW USER OFFER, LIMITED TIME', max_length=50)),
                ('icon_class', models.CharField(default='fa-gift', help_text='FontAwesome icon class', max_length=50)),
                ('gradient_start', models.CharField(default='#667eea', help_text='Hex color code', max_length=7)),
                ('gradient_end', models.CharField(default='#764ba2', help_text='Hex color code', max_length=7)),
                ('button_text', models.CharField(default='Claim Offer', max_length=50)),
                ('button_url', models.CharField(help_text='URL or Django URL name', max_length=200)),
                ('coupon_code', models.CharField(blank=True, help_text='Optional coupon code to display', max_length=50)),
                ('promo_code_text', models.CharField(blank=True, help_text='e.g., Use Code: FIRST50', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
